apiVersion: v1
kind: Service
metadata:
  name: openshift-apiserver
spec:
  clusterIP: ${API_CLUSTERIP}
  selector:
    app: openshift-apiserver
  ports:
  - name: https
    port: 443
    targetPort: 8443
